services:
    nginx:
        image: nginx
        ports:
            - "8000:80"
        volumes:
            - ./public/:/var/www/public/
            - ./:/var/www/
            - ./_docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - php

    php:
        build:
            context: ./_docker/php
        volumes:
            - ./:/var/www

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mpfit_test_task
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "3306:3306"
        volumes:
            - ./db_mpfit_test_task:/var/lib/mysql
        depends_on:
            - php

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "4000:80"
        environment:
            PMA_HOST: db
            PMA_USER: user
            PMA_PASSWORD: user
        depends_on:
            - db

volumes:
    db_mpfit_test_task:
